'm building DevShowcase to help developers organize, run, and monetize their projects—all in one place. It’s modular, open, and designed to spotlight your stack, your workflows, and your creativity.
If you believe in empowering devs to share and scale their work, consider sponsoring me. Your support helps me:
- Keep DevShowcase free and accessible for indie builders
- Add premium features like credit tracking, agent embedding, and direct monetization
- Explore new platforms and integrations (FastAPI, Render, Stripe, Relevance AI)
🛠️ What I’m Working On
- FastAPI wrapper for GPT agents
- Credit-based access and Stripe integration
- Modular stats processor for DevShowcase events
- Landing page and onboarding clarity for users
💸 How to Sponsor
github.com/sponsors/cynlopez53
btcam.gumroad.com/sponsors/53
Thank you for believing in this work.





